### ISSUE TITLE
Please add stylus support

### ISSUE THREAD

**Issue by mwawrusch** [ludohenin/gulp-inline-ng2-template#11]
Or provide a generic means to add compiler support. AFAIK because of express.js most preprocessors use an identical syntax for compilation.

**Comment by mwawrusch** [comment]
also it would be good to include preprocessrors like jade as peerDependencies, and check if they exist before using them.

**Comment by ludohenin** [comment]
@mwawrusch thanks for the suggestion, I'll look into that.

**Comment by mwawrusch** [comment]
Awesome. Msg me at (martin@wawrusch.com) if you need any help. BTW, please publish 0.10.0 to the npm.

**Comment by ludohenin** [comment]
@mwawrusch Maybe we could change the config to look something like
```
{
  template: true,    // deprecate html: true
  template_ext: '.jade',
  template_pre: function () {/* */},    // return string
  template_post: function () {/* */},    // return string
  styles: true,    // deprecate css: true
  styles_ext: '.stylus',
  styles_pre: function () {/* */},    // return string
  styles_post: function () {/* */},    // return string
}
```

I'm not quite sure about the functions' signature.
Would an object like that work ?

```
{
  dirname: string,
  filename: string,
  file: string
}
```

**Comment by mwawrusch** [comment]
I would more likely have an array of configs like:

preprocessors: [

]

**Comment by mwawrusch** [comment]
I would more likely have an array of preprocessors to keep it flexible

```javascript
preprocessors: [
    { extension: /jade/g , require: 'jade',  options: {jade specific options here}, pre: function() {}, post: function() }, ...
]
```

Btw, all those preprocessors have the same calling signature afaik.

**Comment by LuxDie** [comment]
In what scenario would you use more than 2 preprocessors (template & styles)?

**Comment by nareshbhatia** [comment]
@ludohenin, can you please get something out with your proposal (replacing `html` and `css` with `template` and `styles`)? I think it's a good enough abstraction to cover most use cases. The function signature looks good, though I think sending 3 parameters separately might be cleaner. My use case is Sass - I am blocked on my project because this feature is really needed.

Thanks for your help.

**Comment by ludohenin** [comment]
I've preprocessors working now (#20)  ... but struggling a bit with sass.

//cc @mwawrusch @nareshbhatia

**Comment by nareshbhatia** [comment]
Hi @ludohenin, I wanted to drop a quick note regarding my experience with the new preprocessor support. I was trying to add Sass support to Angular 2 Seed. Here's the link to my project: https://github.com/archfirst/angular2-seed-sass.

I initially tried to use this plugin's preprocessor feature by inserting `.scss` urls in my component files:

    @Component({
      selector: 'sd-home',
      moduleId: module.id,
      templateUrl: './home.component.html',
      styleUrls: ['./home.component.scss'],
      directives: [FORM_DIRECTIVES, CORE_DIRECTIVES]
    })

Unfortunately when I tried to make this approach work with the various build workflows (dev, prod, test, e2e), I was having to change the basic angular2-seed workflows too much and the complexity of the build was increasing. Searching for a better solution, I looked at the new [Angular 2 Material](https://github.com/angular/material2) repository created by Google. They are also using Sass. The interesting thing I found was that they are *not* using sass urls in their components - they are sticking to `.css`. This simplifies the build process immensely because you only need to add a preprocessing step to your workflow which creates the `.css` and drops it into the source folder. What I don't like about this approach is that the source folder is now littered with the generated `.css` files, but I am working around this issue by adding these files to my `.gitignore`. This way there is no chance that I will accidentally check in these files.

In addition to simplifying the build, this approach also allows me to use other Sass options that I normally use, e.g. creating source maps that work in conjunction with the generated `.css` files.

Hope this perspective is useful for people who are trying to do similar things with Sass or other preprocessors.
