### ISSUE TITLE
SyntaxError: Unexpected token ]     at replaceFrag

### ISSUE THREAD

**Issue by dasiyes** [ludohenin/gulp-inline-ng2-template#77]
In angular-seed project, while running build.prod scrip, I am getting the following error:

_urls = eval('({' + frag + '})')[opts.prop_url];
                               ^
SyntaxError: Unexpected token ]     at replaceFrag...

The error is at: gulp-inline-ng2-template/parser.js:188

I saw some other guy had the same error. No sure if the issue is reported already or not. Apologies if this is a duplicate.

**Comment by ludohenin** [comment]
This is most likely due to the way you wrote your component decorator options.
Would you provide more info on that, as there is maybe something to improve here.

**Comment by dasiyes** [comment]
Hi 
First of all apologies, for the very "unfriendly" message. I had been in rush and just wanted to sent the info.
 Most likely it was caused by my bad coding. Unfortunately, it was some sand-box testing and I did not capture all the details.

Thanks a lot.

**Comment by ronnyek** [comment]
I am seeing this now too... (your lib is being consumed via ng-packagr).
```
@Component({
  selector: 'iq-df-input',
  templateUrl: './dynamic-form-input.component.html',
  styleUrls: ['./dynamic-form-input.component.scss']
})
```

And I have probably 50 other components that define the style urls the exact same way, and just work. If I remove the styleUrls entry on the component, the in-lining continues (but naturally doesnt include style information on the component).

My question is other than paths (because I am relatively confident that this works elsewhere) like file encoding or bad SCSS or something that would report this error?

**Comment by mitsoe** [comment]
@ronnyek have you found a solution for this by any chance?
